// Action types
const constants = {
  MOVIES_REQUEST: "MOVIES_REQUEST",
  GET_MOVIES: "GET_MOVIES",
  DELETE_MOVIE: "DELETE_MOVIE",
  UPDATE_LIKE_MOVIE: "UPDATE_LIKE_MOVIE",
  FILTER_MOVIES: "FILTER_MOVIES",
};

export default constants;
